# Generated by Django 2.1.7 on 2019-03-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('volunteer1', models.CharField(blank=True, max_length=200, verbose_name='Permanencier 1')),
                ('volunteer2', models.CharField(blank=True, max_length=200, verbose_name='Permanencier 2')),
                ('comment', models.CharField(blank=True, max_length=1000, verbose_name='Commentaire')),
            ],
            options={
                'verbose_name': 'Activité',
            },
        ),
        migrations.CreateModel(
            name='HomePageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField(blank=True, verbose_name='')),
            ],
            options={
                'verbose_name': "Données pour la page d'accueil",
            },
        ),
    ]
