# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permanences', '0002_auto_20171029_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(),
        ),
    ]
