# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permanences', '0003_auto_20171029_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='volunteer1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='volunteer2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
