# Generated by Django 2.1.7 on 2019-03-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permanences', '0004_auto_20171029_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activité'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='volunteer1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Permanencier 1'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='volunteer2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Permanencier 2'),
        ),
    ]
